config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :dish_types
    resources :day_deliveries

    resources :ingredients do
      resources :ingredientimages
    end

    resources :products do

      resource :product_expert

      resources :product_nutritions

    end

    resources :what_you_needs

    resources :nutritions
  end

end

app/controllers/spree/admin/ingredients_controller.rb
module Spree
  module Admin
    class IngredientsController < ResourceController

      def model_class
        Dish::Ingredient
      end

      def index
        respond_with(@collection)
      end

      def show
        redirect_to action: :edit
      end

      def location_after_save
        edit_admin_ingredient_url(@ingredient)
      end

      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        params[:q][:deleted_at_null] ||= "1"

        params[:q][:s] ||= "name asc"
        @collection = super
        if params[:q].delete(:deleted_at_null) == '0'
          @collection = @collection.with_deleted
        end
        # @search needs to be defined as this is passed to search_form_for
        @search = @collection.ransack(params[:q])
        @collection = @search.result.
              page(params[:page]).
              per(params[:per_page] || Spree::Config[:admin_products_per_page])

        @collection
      end
    end
  end
end

app/views/spree/admin/ingredients/_form.html.erb
<div data-hook="new_ingredient_attrs" class="row">
  <div class="alpha twelve columns">
    <%= f.label :name, Spree.t(:ingredient_name)%>
    <%= f.text_field :name, name: "ingredient[name]", :class => 'fullwidth title'%>
    <%= f.error_message_on :name %>
  </div>
<div class="clear"></div>

app/views/spree/admin/ingredients/edit.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_ingredients_list), admin_ingredients_url, :icon => 'arrow-left' %></li>
  <% if can?(:create, Dish::Ingredient) %>
    <li id="new_ingredient_link">
      <%= button_link_to Spree.t(:new_ingredient), new_admin_ingredient_url, {:icon => 'plus', :id => 'admin_new_ingredient' } %>
    </li>
  <% end %>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu'%>

<%= render :partial => 'spree/admin/shared/ingredient_tabs', :locals => {:current => 'Ingredient Details'}%>

<%= form_for @ingredient, method: :put, :url => admin_ingredient_url(@ingredient), :html => {:id => "edit_ingredient", :multipart => true} do |f| %>
  <fieldset data-hook="edit-ingredient">
    <%= render :partial => "form", :locals => {:f => f} %>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'ok' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_ingredient_url, :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/ingredients/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_ingredients) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_ingredient_link">
    <%= button_link_to Spree.t(:new_ingredient), new_admin_ingredient_url, { :remote => true, :icon => 'plus', :id => 'new_ingredient_link' } %>
  </li>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<div id="new_ingredient_wrapper" data-hook></div>

<%= paginate @ingredients %>

<% if @ingredients.any? %>
  <table>
    <colgroup>
      <col style="width: 30%;" />
      <col style="width: 60%;" />
      <col style="width: 10%;" />
    </colgroup>
    <thead>
      <tr>
        <th><%=Spree.t(:image)%></th>
        <th><%=Spree.t(:name)%></th>
      </tr>
    </thead>
    <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <% if ingredient.images.any? %>
          <td class="align-center"><%= image_tag ingredient.images.first.attachment.url(:mini) %></td>
        <% else %>
          <td class="align-center"></td>
        <% end %>
        <td class="align-center">
          <%= link_to ingredient.name, admin_ingredient_url(ingredient) %>
        </td>
        <td class="actions" data-hook="admin_ingredients_index_row_actions">
          <%= link_to_edit ingredient, :no_text => true, :class => 'edit' if can?(:edit, ingredient)%>
          &nbsp;
          <%= link_to_delete ingredient, :no_text => true if can?(:delete, ingredient)%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= Spree.t(:no_experts_found) %>.
  </div>
<% end %>

<%= paginate @ingredients %>

app/views/spree/admin/ingredients/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= form_for @ingredient, url: admin_ingredients_url(@ingredient), method: 'POST', html: { id: "new_ingredient", multipart: true } do |f|%>
  <fieldset data-hook="new_ingredient">
    <legend align="center"><%= Spree.t(:new_ingredient) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <%= render :partial => 'spree/admin/shared/new_ingredient_links' %>

  </fieldset>
<% end %>

app/views/spree/admin/ingredients/new.js.erb
$("#new_ingredient_wrapper").html('<%= escape_javascript(render :template => "spree/admin/ingredients/new", :formats => [:html], :handlers => [:erb]) %>');
handle_date_picker_fields();
<% unless Rails.env.test? %>
  $('.select2').select2();
<% end %>
$("#table-filter").hide();
$("#admin_new_ingredient").parent().hide();