config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :dish_types
    resources :day_deliveries

    resources :ingredients do
      resources :ingredientimages
    end

    resources :products do

      resource :product_expert

      resources :product_nutritions

    end

    resources :what_you_needs

    resources :nutritions
  end

end

app/controllers/spree/admin/ingredientimages_controller.rb
module Spree
  module Admin
    class IngredientimagesController < ResourceController
      before_action :load_data

      create.before :set_viewable
      update.before :set_viewable

      def model_class
        Dish::IngredientImage
      end

      def edit
      end

      def new
        @ingredientimage = @ingredient.images.build
        render :layout => false 
      end

      private 
        def location_after_destroy
          admin_ingredient_ingredientimages_url(@ingredient)
        end

        def location_after_save
          admin_ingredient_ingredientimages_url(@ingredient)
        end

        def load_data
          @ingredient = Dish::Ingredient.find(params[:ingredient_id])
        end

        def set_viewable
          @ingredientimage.viewable_type = 'Dish::Ingredient'
          @ingredientimage.viewable_id = params[:ingredientimage][:viewable_id]
        end
    end
  end
end

app/views/spree/admin/ingredientimages/_form.html.erb
<div data-hook="admin_image_form_fields">
  <div class="four columns alpha">
    <div data-hook="file" class="field">
      <%= f.label :attachment, Spree.t(:filename) %><br>
      <%= f.file_field :attachment, name: "ingredientimage[attachment]", accept: 'image/png,image/gif,image/jpeg' %>
    </div>
    <div data-hook="variant" class="field">
      <%= f.hidden_field :viewable_id, name: "ingredientimage[viewable_id]", :value => @ingredientimage.viewable_id %><br>
    </div>
  </div>
  <div data-hook="alt_text" class="field omega five columns">
    <%= f.label :alt, Spree.t(:alt_text) %><br>
    <%= f.text_area :alt, rows: 4, class: 'fullwidth' %>
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/ingredientimages/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/ingredient_tabs', :locals => {:current => 'Images'}%>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_images_list), admin_ingredient_ingredientimages_url(@ingredient), :icon => 'arrow-left' %></li>
<% end %>

<%= form_for [@ingredient, @ingredientimage], url: admin_ingredient_ingredientimage_url, :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_image">
    <legend align="center"><%= @ingredientimage.attachment_file_name%></legend>
    <div data-hook="thumbnail" class="field alpha three columns align-center">
      <%= f.label Spree.t(:thumbnail) %><br>
      <%= link_to image_tag(@ingredientimage.attachment.url(:mini)), @ingredientimage.attachment.url(:ingredient) %>
    </div>
    <div class="nine columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>  
    </div>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to Spree.t('actions.cancel'), admin_ingredient_ingredientimages_url(@ingredient), :id => 'cancel_link', :class => 'button remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/ingredientimages/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/ingredient_tabs', :locals => {:current => 'Images'}%>

<!--Button add new image-->
<% content_for :page_actions do %>
  <% if !@ingredient.images.any? %>
    <li><%= link_to_with_icon('plus', Spree.t(:new_image), new_admin_ingredient_ingredientimage_url(@ingredient), :id => 'new_image_link', :class => 'button') %></li>
  <% else %>
    <li></li>
  <% end %>
<% end %>


<div id="images" data-hook></div>

<!--Display images-->
<% unless @ingredient.images.any? %>
  <div class="no-objects-found">
    <%= Spree.t(:no_images_found) %>.
  </div>
<% else %>
  <table data-hook="images_table"%>
    <thead>
      <tr data-hook="images_header">
        <th colspan="2"><%= Spree.t(:thumbnail) %></th>
        <th><%= Spree.t(:alt_text) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@ingredient.images).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
          </td>
          <td class="align-center">
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:normal) %>
          </td>

          <td><%= image.alt %></td>
          <td class="actions">
            <%= link_to_with_icon 'edit', Spree.t(:edit), edit_admin_ingredient_ingredientimage_url(@ingredient, image), :no_text => true, :data => {:action => 'edit'} %>
            <%= link_to_delete image, { :url => admin_ingredient_ingredientimage_url(@ingredient, image), :no_text => true } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/ingredientimages/new.html.erb
<%= form_for [@ingredient, @ingredientimage], url: admin_ingredient_ingredientimages_url(@ingredient), method: 'POST', :html => { :multipart => true,:id => 'new_ingredientimage', :class => 'new_ingredientimage' } do |f| %>
  <fieldset data-hook="new_image">
    <legend align="center"><%= Spree.t(:new_image) %></legend>

      <%= render :partial => 'form', :locals => { :f => f } %>
    
      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t('actions.create'), 'refresh' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_ingredient_ingredientimages_url(@ingredient), :id => 'cancel_link', :class => 'button' %>
      </div>
  </fieldset>
<% end %>

<%= javascript_include_tag 'spree/backend/images/new.js' %>