config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :dish_types
    resources :day_deliveries

    resources :ingredients do
      resources :ingredientimages
    end

    resources :products do

      resource :product_expert

      resources :product_nutritions

    end

    resources :what_you_needs

    resources :nutritions
  end

end

app/models/spree/product.rb
module Spree
  class Product < Spree::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: :history

    acts_as_paranoid

    has_many :classifications, dependent: :delete_all, inverse_of: :product

    has_and_belongs_to_many :promotion_rules, join_table: :spree_products_promotion_rules

    has_many :line_items, through: :variants_including_master
    has_many :orders, through: :line_items

    # delegate :images, to: :master, prefix: true
    # alias_method :images, :master_images
    has_one :master,
      -> { where is_master: true },
      inverse_of: :product,
      class_name: 'Spree::Variant'

    has_many :variants_including_master,
      -> { order("#{::Spree::Variant.quoted_table_name}.position ASC") },
      inverse_of: :product,
      class_name: 'Spree::Variant',
      dependent: :destroy

    has_many :variants,
      -> { where(is_master: false).order("#{::Spree::Variant.quoted_table_name}.position ASC") },
      inverse_of: :product,
      class_name: 'Spree::Variant'


    has_many :variant_images, -> { order(:position) }, source: :images, through: :variants_including_master

    after_destroy :punch_slug

    after_save :run_touch_callbacks, if: :anything_changed?
    after_save :reset_nested_changes
    after_save :save_master
    after_initialize :ensure_master

    before_validation :normalize_slug, on: :update
    validates :name, presence: true
    validates :slug, length: { minimum: 3 }, uniqueness: { allow_blank: true }

    def ensure_master
      return unless new_record?
      self.master ||= build_master
    end

    def save_master
      if master && (master.changed? || master.new_record? || (master.default_price && (master.default_price.changed? || master.default_price.new_record?)))
        master.save!
        @nested_changes = true
      end
    end

    def has_variants?
      variants.any?
    end

    def duplicate
      duplicator = ProductDuplicator.new(self)
      duplicator.duplicate
    end

    def deleted?
      !!deleted_at
    end

    def available?
      !(available_on.nil? || available_on.future?) && !deleted?
    end


    def self.like_any(fields, values)
      where fields.map { |field|
        values.map { |value|
          arel_table[field].matches("%#{value}%")
        }.inject(:or)
      }.inject(:or)
    end

    def possible_promotions
      promotion_ids = promotion_rules.map(&:promotion_id).uniq
      Spree::Promotion.advertised.where(id: promotion_ids).reject(&:expired?)
    end

    private

    def normalize_slug
      self.slug = normalize_friendly_id(slug)
    end

    def punch_slug
      update_column :slug, "#{Time.now.to_i}_#{slug}" # punch slug with date prefix to allow reuse of original
    end

    def anything_changed?
      changed? || @nested_changes
    end

    def reset_nested_changes
      @nested_changes = false
    end

    # Try building a slug based on the following fields in increasing order of specificity.
    def slug_candidates
      [
        :name
      ]
    end

    def run_touch_callbacks
      run_callbacks(:touch)
    end

  end
end

require_dependency 'spree/product/scopes'

app/controllers/spree/admin/products_controller.rb
module Spree
  module Admin
    class ProductsController < ResourceController
      helper 'spree/products'

      before_action :load_data, except: :index
      # create.before :create_before
      # update.before :update_before
      helper_method :clone_object_url
      helper_method :dishtype

      def show
        session[:return_to] ||= request.referer
        redirect_to action: :edit
      end

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def update

        if (params[:product][:dish_price])

          price = params[:product][:dish_price];

          price = price.gsub("VND", "")

          price = price.gsub(",", "")

          params[:product][:dish_price] = price.delete(' ')
        end

        if params[:product][:ingredient_ids].present?
          params[:product][:ingredient_ids] = params[:product][:ingredient_ids].split(',')
        end

        if params[:product][:whatneed_ids].present?
          params[:product][:whatneed_ids] = params[:product][:whatneed_ids].split(',')
        end

        if params[:product][:nutrition_ids].present?
          params[:product][:nutrition_ids] = params[:product][:nutrition_ids].split(',')
        end
        invoke_callbacks(:update, :before)
        if @object.update_attributes(permitted_resource_params)
          invoke_callbacks(:update, :after)
          flash[:success] = flash_message_for(@object, :successfully_updated)
          respond_with(@object) do |format|
            format.html { redirect_to location_after_save }
            format.js   { render layout: false }
          end
        else
          # Stops people submitting blank slugs, causing errors when they try to
          # update the product again
          @product.slug = @product.slug_was if @product.slug.blank?
          invoke_callbacks(:update, :fails)
          respond_with(@object)
        end
      end

      def destroy
        @product = Product.friendly.find(params[:id])
        @product.destroy

        flash[:success] = Spree.t('notice_messages.product_deleted')

        respond_with(@product) do |format|
          format.html { redirect_to collection_url }
          format.js  { render_js_for_destroy }
        end
      end

      def clone
        @new = @product.duplicate

        if @new.save
          flash[:success] = Spree.t('notice_messages.product_cloned')
        else
          flash[:error] = Spree.t('notice_messages.product_not_cloned')
        end

        redirect_to edit_admin_product_url(@new)
      end

      # def product_expert
      #   if !@product.expert
      #     @expert = model_class.new
      #   else 
      #     @expert = @product.expert
      #  end

      #   render :json => @expert
      # end

      protected

      def find_resource
        Product.with_deleted.friendly.find(params[:id])
      end

      def location_after_save
        spree.edit_admin_product_url(@product)
      end

      def load_data
        #@ingredients = Dish::Ingredient.order(:name)
        #@whatneeds = Dish::Whatneed.order(:name)
        #@nutritions = Dish::Nutrition.order(:name)
        #@shipping_categories = ShippingCategory.order(:name)
        @dish_types = Dish::DishType.order(:name)
        @difficulties = Dish::Difficulty.all
      end

      # def get_ingredients
      #   return if option_values_hash.nil?
      #   option_values_hash.keys.map(&:to_i).each do |id|
      #     self.option_type_ids << id unless option_type_ids.include?(id)
      #     product_option_types.create(option_type_id: id) unless product_option_types.pluck(:option_type_id).include?(id)
      #   end
      # end

      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        params[:q][:deleted_at_null] ||= "1"
        
        params[:q][:s] ||= "name asc"
        @collection = super
        if params[:q].delete(:deleted_at_null) == '0'
          @collection = @collection.with_deleted
        end
        # @search needs to be defined as this is passed to search_form_for
        @search = @collection.ransack(params[:q])
        @collection = @search.result.
              distinct_by_product_ids(params[:q][:s]).
              #includes(product_includes).
              page(params[:page]).
              per(params[:per_page] || Spree::Config[:admin_products_per_page])

        @collection
      end

      # def create_before
      #   return if params[:product][:prototype_id].blank?
      #   @prototype = Spree::Prototype.find(params[:product][:prototype_id])
      # end

      # def update_before
      #   # note: we only reset the product properties if we're receiving a post
      #   #       from the form on that tab
      #   return unless params[:clear_product_properties]
      #   params[:product] ||= {}
      # end

      # def product_includes
      #   [{ variants: [:images], master: [:images, :default_price] }]
      # end

      def clone_object_url(resource)
        clone_admin_product_url resource
      end

      def dishtype(id)
        dishtype = Dish::DishType.find(:id)
        puts "IDDDDDDDDDDDDDDDDDDDDDD: ", id
        return dishtype.name
      end

      private

      # def variant_stock_includes
      #   [:images, stock_items: :stock_location, option_values: :option_type]
      # end
    end
  end
end

app/views/spree/admin/products/_autocomplete.js.erb
<script type='text/template' id='product_template'>
  <li id="product_{{ product.id }}" data-product-id="{{product.id }}" class="columns three alpha small_product">
    <div class="product-image">
      {{#if product.image }}
        <img src='{{product.image}}' alt='{{ product.name }}' />
      {{ else }}
        <img src='<%= image_path("noimage/small.png") %>' alt='{{product.name }}' />
      {{/if}}
    </div>
    <a class="name">{{ product.name }}</a><br>
    <span class="price">{{ product.display_price }}</span>
  </li>
</script>

app/views/spree/admin/products/_form.html.erb
<div data-hook="admin_product_form_fields">

  <div class="left eight columns alpha" data-hook="admin_product_form_left">
    <div data-hook="admin_product_form_name">
      <%= f.field_container :name do %>
        <%= f.label :name, raw(Spree.t(:name) + content_tag(:span, ' *', :class => 'required')) %>
        <%= f.text_field :name, :class => 'fullwidth title', :required => true %>
        <%= f.error_message_on :name %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_story">
      <%= f.field_container :story do %>
        <%= f.label :story, Spree.t(:story) %>
        <%= f.text_area :story, {:rows => 10, :class => 'fullwidth'} %>
        <%= f.error_message_on :story %>
      <% end %>
    </div>
  </div>

  <div class="right four columns omega" data-hook="admin_product_form_right">

    <div data-hook="admin_product_form_price">
    <%= f.field_container :dish_price do %>
      <%= f.label :dish_price, raw(Spree.t(:dish_price) + content_tag(:span, ' *', :class => "required")) %>
      <%= f.text_field :dish_price, :value => number_to_currency(@product.dish_price, :unit => 'VND', precision: 0, seperator: ".", format: "%n %u"), :required => true %>
      <%= f.error_message_on :dish_price %>
    <% end %>
    </div>

    <div class="clear"></div>

    <!-- <div data-hook="admin_product_form_available_on">
      <%= f.field_container :available_on do %>
        <%= f.label :available_on, Spree.t(:available_on) %>
        <%= f.error_message_on :available_on %>
        <%= f.text_field :available_on, :value => datepicker_field_value(@product.available_on), :class => 'datepicker' %>
      <% end %>
    </div>
 -->
    <!-- <div data-hook="admin_product_form_promotionable">
      <%= f.field_container :promotionable do %>
        <%= f.label :promotionable do %>
          <%= f.check_box :promotionable %> <%= Spree.t(:promotionable) %>
        <% end %>
      <% end %>
    </div> -->

    <div data-hook="admin_product_form_dish_types">
      <%= f.field_container :dish_type do %>
        <%= f.label :dish_type_id, Spree.t(:dish_types) %>
        <%= f.collection_select(:dish_type_id, @dish_types, :id, :name, { :include_blank => false }, { :class => 'select2' }) %>
        <%= f.error_message_on :dish_type %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_difficulty">
      <%= f.field_container :difficulty do %>
        <%= f.label :difficulty_id, Spree.t(:difficulty) %>
        <%= f.collection_select(:difficulty_id, @difficulties, :id, :name, { :include_blank => false }, { :class => 'select2' }) %>
        <%= f.error_message_on :difficulty_id %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_time_cook">
      <%= f.field_container :time_cook do %>
        <%= f.label :time_cook, Spree.t(:time_cook) + " (min)" %>
        <%= f.text_field :time_cook, type: "number" %>
        <%= f.error_message_on :time_cook %>
      <% end %>
    </div>

  </div>

  <div class="twelve columns alpha omega">

    <div data-hook="admin_product_form_ingredients">
      <%= f.field_container :ingredients do %>
        <%= f.label :ingredient_ids, Spree.t(:ingredients) %>
        <%= f.hidden_field :ingredient_ids, :value => @product.ingredient_ids.join(',') %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_what_you_needs">
      <%= f.field_container :whatneeds do %>
        <%= f.label :whatneed_ids, Spree.t(:what_you_needs) %>
        <%= f.hidden_field :whatneed_ids, :value => @product.whatneed_ids.join(',') %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_nutritions">
      <%= f.field_container :nutritions do %>
        <%= f.label :nutrition_ids, Spree.t(:nutritions) %>
        <%= f.hidden_field :nutrition_ids, :value => @product.nutrition_ids.join(',') %>
      <% end %>
    </div>

  </div>

  <div class="clear"></div>

  <div data-hook="admin_product_form_additional_fields"></div>

  <div class="clear"></div>

</div>

<% unless Rails.env.test? %>
  <script>
  $('.select2-container').css({width: '20em'})
  </script>
<% end %>

app/views/spree/admin/products/_properties_form.erb
<% content_for :page_title do %>
  <%= Spree.t(:properties) %>
<% end %>

<% f.fields_for :product_properties do |properties_form| %>
    <div data-hook="value">
      <%= properties_form.label :value, properties_form.object.property.presentation %><br />
      <%= properties_form.text_field :value %>
    </div>
<% end %>

app/views/spree/admin/products/edit.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_products_list), session[:return_to] || admin_products_url, :icon => 'arrow-left' %></li>
  <% if can?(:create, Spree::Product) %>
    <li id="new_product_link">
      <%= button_link_to Spree.t(:new_product), new_object_url, { :icon => 'plus', :id => 'admin_new_product' } %>
    </li>
  <% end %>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Product Details' } %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product } %>

<%= form_for [:admin, @product], :method => :put, :html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/products/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_products) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_product_link">
    <%= button_link_to Spree.t(:new_product), new_object_url, { :remote => true, :icon => 'plus', :id => 'admin_new_product' } %>
  </li>
<% end if can?(:create, Spree::Product) %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>

        <%- locals = {:f => f} %>

        <div data-hook="admin_products_index_search">
          <div class="alpha sixteen columns">
            <div class="field">
              <%= f.label :name_cont, Spree.t(:name) %>
              <%= f.text_field :name_cont, :size => 15 %>
            </div>
          </div>
        </div>

        <div class="clear"></div>

        <div class="form-buttons actions filter-actions" data-hook="admin_products_index_search_buttons">
          <%= button Spree.t(:search), 'search' %>
        </div>
    <% end %>
  </div>
<% end %>

<div id="new_product_wrapper" data-hook></div>

<%= paginate @collection %>

<% if @collection.any? %>
  <table class="index" id="listing_products">
    <colgroup>
       <col style="width: 15%;">
       <col style="width: 40%;">
       <col style="width: 16%;">
       <col style="width: 12%;">
       <col style="width: 17%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:image) %></th>
        <th><%= sort_link @search,:name, Spree.t(:name), { :default_order => "desc" }, {:title => 'admin_products_listing_name_title'} %></th>
        <th><%= sort_link @search,:dish_type_id, Spree.t(:type), {}, {:title => 'admin_products_listing_type_title'} %></th>
        <th><%= sort_link @search,:dish_price, Spree.t(:master_price), {}, {:title => 'admin_products_listing_price_title'} %></th>
        <th data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |product| %>
          <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <% if product.variant_images.any? %>
              <td class="align-center"><%= image_tag product.variant_images[0].attachment.url(:mini) %></td>
            <% else %>
              <td class="align-center"></td>
            <% end %>
            <td class="align-center"><%= link_to product.try(:name), edit_admin_product_path(product) %></td>
            <td class="align-center"><%= product.dish_type.name rescue '' %></td>
            <td class="align-center"><%= number_to_currency(product.dish_price, :unit => 'VND', precision: 0, seperator: ".", format: "%n %u") rescue '' %></td>
            <td class="actions" data-hook="admin_products_index_row_actions">
              <%= link_to_edit product, :no_text => true, :class => 'edit' if can?(:edit, product) && !product.deleted? %>
              &nbsp;
              <%= link_to_clone product, :no_text => true, :class => 'clone' if can?(:clone, product) %>
              &nbsp;
              <%= link_to_delete product, :no_text => true if can?(:delete, product) && !product.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/product')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_product_path %>!
  </div>
<% end %>

<%= paginate @collection %>

app/views/spree/admin/products/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product } %>

<%= form_for [:admin, @product], method: :post, url: admin_products_path, :html => { :multipart => true } do |f| %>

  <fieldset data-hook="new_product">

    <legend align="center"><%= Spree.t(:new_product) %></legend>

    <%= f.field_container :name do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
      <%= f.text_field :name, :class => 'fullwidth title', :required => true %>
      <%= f.error_message_on :name %>
    <% end %>

    <div data-hook="new_product_attrs" class="row">

      <div data-hook="new_product_dish_type" class="alpha four columns">
        <%= f.field_container :dish_type do %>
          <%= f.label :dish_type_id, Spree.t(:dish_type) %><br />
          <%= f.collection_select :dish_type_id, Dish::DishType.all, :id, :name, {:include_blank => false}, {:class => 'select2 fullwidth'} %>
        <% end %>
      </div>

      <div data-hook="new_product_price" class="four columns">
        <%= f.field_container :dish_price do %>
          <%= f.label :dish_price, Spree.t(:master_price) %> <span class="required">*</span><br />
          <%= f.text_field :dish_price, :value => number_to_currency(@product.dish_price, :unit => ''), :class => 'fullwidth', :required => true %>
          <%= f.error_message_on :dish_price %>
        <% end %>
      </div>

    </div>

    <div class="clearfix" data-hook="product-from-prototype" id="product-from-prototype">
      <%= render :file => 'spree/admin/prototypes/show' if @prototype %>
    </div>

    <%= render :partial => 'spree/admin/shared/new_resource_links' %>

  </fieldset>
<% end %>

<script type="text/javascript">
//<![CDATA[
  (function($){
    var base_url = "<%= admin_prototypes_url %>";
    var prototype_select = $('#product_prototype_id');
    prototype_select.change(function() {
      var id = prototype_select.val();
      if (id.length) {
        var url = new Uri(base_url);
        url.setPath(url.path() + '/' + id);
        $('#product-from-prototype').load(url.toString());
      } else {
        $('#product-from-prototype').empty();
      }
    })
    if (prototype_select.html() == "") {
      prototype_select.change();
    }
  })(jQuery);
//]]>
</script>

app/views/spree/admin/products/new.js.erb
$("#new_product_wrapper").html('<%= escape_javascript(render :template => "spree/admin/products/new", :formats => [:html], :handlers => [:erb]) %>');
handle_date_picker_fields();
<% unless Rails.env.test? %>
  $('.select2').select2();
<% end %>
$("#table-filter").hide();
$("#admin_new_product").parent().hide();