config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :dish_types
    resources :day_deliveries

    resources :ingredients do
      resources :ingredientimages
    end

    resources :products do

      resource :product_expert

      resources :product_nutritions

    end

    resources :what_you_needs

    resources :nutritions
  end

end

app/views/spree/admin/shared/_edit_product_nutrition_links.erb
<div class="form-buttons filter-actions actions" data-hook="buttons">
  <%= button Spree.t('actions.update'), 'refresh' %>
  <span class="or"><%= Spree.t(:or) %></span>
  <%= button_link_to Spree.t('actions.cancel'), admin_product_product_nutrition_url(@nutrition) , :icon => 'remove' %>
</div>

app/views/spree/admin/shared/_head.html.erb
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />

<%= csrf_meta_tags %>

<title>
  <% if content_for? :title %>
    <%= yield :title %>
  <% else %>
    <%= "Spree #{Spree.t('administration')}: " %>
    <%= Spree.t(controller.controller_name, :default => controller.controller_name.titleize) %>
  <% end %>
</title>

<!-- Get "Open Sans" font from Google -->
<link href='//fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600&subset=latin,cyrillic,greek,vietnamese' rel='stylesheet' type='text/css'>

<%= stylesheet_link_tag 'spree/backend/all' %>

<%= javascript_include_tag 'spree/backend/all' %>

<%= render "spree/admin/shared/translations" %>
<%= render "spree/admin/shared/dish_translations" %>

<%= javascript_tag do -%>
  jQuery.alerts.dialogClass = 'spree';
  <%== "var AUTH_TOKEN = #{form_authenticity_token.inspect};" %>
  <%== "Spree.api_key = '#{try_spree_current_user.spree_api_key}';" if try_spree_current_user %>
<% end %>

<%= yield :head %>

app/views/spree/admin/shared/_ingredient_tabs.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_ingredient) %> &ldquo;<%= @ingredient.name %>&rdquo;
<% end %>

<% content_for :sidebar_title do %>
  <span class="sku"><%= @ingredient.name %></span>
<% end %>

<% content_for :sidebar do %>
  <nav class="menu">
    <ul data-hook="admin_box_tabs">
      <%= content_tag :li, :class => ('active' if current == 'Ingredient Details') do %>
        <%= link_to_with_icon 'edit', Spree.t(:ingredient_details), edit_admin_ingredient_url(@ingredient) %>
      <% end if can?(:admin, Dish::Ingredient) %>
      <%= content_tag :li, :class => ('active' if current == 'Images') do %>
        <%= link_to_with_icon 'picture-o', Spree.t(:images), admin_ingredient_ingredientimages_url(@ingredient) %>
      <% end if can?(:admin, Dish::Ingredient) %>
    </ul>
  </nav>
<% end %>

app/views/spree/admin/shared/_new_dish_type_links.erb
<div class="form-buttons filter-actions actions" data-hook="buttons">
  <%= button Spree.t('actions.create'), 'ok' %>
  <span class="or"><%= Spree.t(:or) %></span>
  <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), new_admin_nutrition_url, :class => 'button' %>
</div>

app/views/spree/admin/shared/_new_ingredient_links.erb
<div class="form-buttons filter-actions actions" data-hook="buttons">
  <%= button Spree.t('actions.create'), 'ok' %>
  <span class="or"><%= Spree.t(:or) %></span>
  <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), new_admin_ingredient_url, :class => 'button' %>
</div>

app/views/spree/admin/shared/_new_nutrition_links.erb
<div class="form-buttons filter-actions actions" data-hook="buttons">
  <%= button Spree.t('actions.create'), 'ok' %>
  <span class="or"><%= Spree.t(:or) %></span>
  <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), new_admin_dish_type_url, :class => 'button' %>
</div>

app/views/spree/admin/shared/_new_what_you_need_links.erb
<div class="form-buttons filter-actions actions" data-hook="buttons">
  <%= button Spree.t('actions.create'), 'ok' %>
  <span class="or"><%= Spree.t(:or) %></span>
  <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), new_admin_what_you_need_url, :class => 'button' %>
</div>

app/views/spree/admin/shared/_product_sub_menu.html.erb
<% content_for :sidebar_title do %>
  <%= Spree.t(:dishes) %>
<% end %>

<% content_for :sub_menu do %>
  <ul id="sub_nav" data-hook="admin_product_sub_tabs" class="inline-menu">
    <%= tab :products, :match_path => '/products'%>
    <%= tab :dish_types %>
    <%= tab :day_deliveries %>
    <%= tab :ingredients, :match_path => '/ingredients' %>
    <%= tab :what_you_needs %>
    <%= tab :nutritions %>
  </ul>
<% end %>

app/views/spree/admin/shared/_product_tabs.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_product) %> &ldquo;<%= @product.name %>&rdquo;
<% end %>

<% content_for :sidebar_title do %>
  <span class="sku"><%= Spree.t("Menu") %></span>
<% end %>

<% content_for :sidebar do %>
  <nav class="menu">
    <ul data-hook='admin_product_tabs'>
      <%= content_tag :li, :class => ('active' if current == 'Product Details') do %>
        <%= link_to_with_icon 'edit', Spree.t(:product_details), edit_admin_product_url(@product) %>
      <% end if can?(:admin, Spree::Product) %>
      <%= content_tag :li, :class => ('active' if current == 'Images') do %>
        <%= link_to_with_icon 'picture-o', Spree.t(:images), admin_product_images_url(@product) %>
      <% end if can?(:admin, Spree::Image) %>
      <%= content_tag :li, :class => ('active' if current == 'Experts') do %>
        <%= link_to_with_icon 'picture-o', Spree.t(:experts), admin_product_product_expert_url(@product) %>
      <% end if can?(:box_expert, Bm::Expert) %>
      <%= content_tag :li, :class => ('active' if current == 'Nutritions') do %>
        <%= link_to_with_icon 'picture-o', Spree.t(:nutritions), admin_product_product_nutritions_url(@product) %>
      <% end if can?(:admin, Dish::Nutrition) %>
    </ul>
  </nav>

<% end %>